baseURL = 'https://gloria.ma/'
languageCode = 'en-us'
title = 'Gloria Ma'
buildFuture = true
enableGitInfo = true

[params.hypothesis]
  enabled = true
  sections = ["blog", "uknowme"]
  inline = true
